### ISSUE TITLE
Unable to build - camera issue

### ISSUE THREAD

**Issue by mbnoimi** [dineshdb/photomanager#5]
I'm unable to build it under Linux Mint 18.2 x64 xfce

```
[ 11%] Building CXX object build/camera/CMakeFiles/camera.dir/main.cc.o
build/camera/CMakeFiles/camera.dir/build.make:62: recipe for target 'build/camera/CMakeFiles/camera.dir/main.cc.o' failed
CMakeFiles/Makefile2:117: recipe for target 'build/camera/CMakeFiles/camera.dir/all' failed
Makefile:127: recipe for target 'all' failed
```

NOTE: 
* cmake run smoothly
* I use this revision https://github.com/dineshdb/photomanager/commit/1479be2df2f909043750dd6691ed5efd2b6859a9

**Comment by dineshdb** [comment]
It's compiling fine in my pc. So i can't deduce the problem based on info you provided. Please provide full log so that I can see the problem. Plus, nothing much is done in camera, you can safely ignore this build if other components are built.

Details Needed:
Full make log, cmake log(recommended)
Development Env (OS, versions, gcc, etc).
